python-chromedriver-selenium/Dockerfile, python-chromedriver-selenium/README.md, python-chromedriver-selenium/metadata.yml
=> python-chromedriver-selenium now based on debian.

perfsonar-checker/supervisord.conf
Fixing https://github.com/slateci/docker-images/issues/9
=> Fixing #9 perfsonar-checker Docker broken

build.py, condor-login/Dockerfile, condor-manager/Dockerfile, condor-submit/Dockerfile, condor-worker/Dockerfile, fts3/Dockerfile, globus-connect-v4/Dockerfile, gridftp/Dockerfile, login-node/Dockerfile, mariadb/Dockerfile, minio/Dockerfile, open-ondemand/Dockerfile
=> Feature/30 the following images failed to build (hadolint)

minislate/Dockerfile, minislate/metadata.yml
=> minislate: v1.0.5 with updated pip requirements.txt path

slate-client-server/Dockerfile, slate-client-server/metadata.yml, slate-client-server/scripts/install-dynamo.sh
=> slate-client-server: 1.0.9 - local DynamoDB now included

.github/workflows/force-build.yml, .github/workflows/pr-close.yml, .github/workflows/pr-post-build.yml, .github/workflows/pr.yml, .github/workflows/push.yml, README.md, build.py
See #39 for more details. Going to have to test these changes after the merge.
=> First pass at removing GitHub packages from GitHub workflow files.

example/metadata.yml
=> Test changes to example image.

.github/workflows/push.yml
=> Added slack notifications to push.yml github workflow.

build_folders.txt, slate-client-alpine/Dockerfile
=> Base os is Alpine 3.11.6 and added static libs

globus-connect-v4/Dockerfile
=> Update Globus to 4.0.63

.github/workflows/push.yml, globus-connect-v4/Dockerfile
=> 82 grep no such file or directory errors for tj actionschanged files in pushyml

.github/workflows/push.yml, globus-connect-v4/Dockerfile
=> Switching to CSV format for container tags passed as output in push.yml

helm-gcloud-sdk/README.md, slate-client-server/Dockerfile, slate-client-server/scripts/install-aws-cpp-sdk.sh
=> Rocky update

slate-client-server/Dockerfile
=> Bumped image version to 2.0.1 and now using pre-built AWS C++ SDK.

condor-worker/Dockerfile
=> Content dump from old SLATE stable catalog.

slate-client-server/Dockerfile, slate-client-server/scripts/install-aws-cpp-sdk.sh, slate-client-server/scripts/install-opentelemetry.sh
=> Modified slate-client-server to make use of new static build of opentel c++ client.

helm-gcloud-sdk/Dockerfile, helm-gcloud-sdk/README.md
=> Dependency updates for helm-gcloud-sdk

slate-client-alpine/Dockerfile, slate-client-alpine/README.md, slate-client-server/Dockerfile, slate-client-server/README.md
=> 112 slate client server | alpine add support for using ccache

slate-client-alpine/Dockerfile, slate-client-server/Dockerfile
Cheating and keeping current image versions.
=> Removed cache envs from slate-client-alpine and slate-client-server.

minislate/Dockerfile
=> Moved location of slate_portal_user in image.

.github/workflows/push.yml, helm-gcloud-sdk/Dockerfile
=> 162 deprecated set output commands in GitHub workflows

slate-client-server/Dockerfile
=> Added 'allowerasing' for libcurl package in slate-client-server.

.github/workflows/push.yml, helm-gcloud-sdk/Dockerfile, slate-client-alpine/Dockerfile, slate-client-server/Dockerfile
=> 195 add multi arch support

v4a/Dockerfile
=> Added image labels to v4a/Dockerfile.

atlas-xcache-heartbeats/Dockerfile, v4a/Dockerfile
=> Added Ilija as an author for atlas-xcache-heartbeats and v4a.
